config/routes.rb
Rails.application.routes.draw do
  root to: "bands#index"  
  
  resources :bands
  
  devise_for :users 

  # post "/bands/create", to: "bands#create"
  # get "/bands/new", to: "bands#new", as: "bands_new"
  # #to edit
  # get "/bands/:id/edit", to: "bands#edit", as: "bands_edit"
  # #update
  # get "/bands/:id", to: "bands#show", as: "band"
  # put "/bands/:id", to: "bands#update"
  # patch "/bands/:id", to: "bands#update"
  # delete "/bands/:id", to: "bands#destroy"

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new
    can [:index, :show, :new, :create], Band
    can [:edit, :update, :destroy], Band, user_id: user.id
  end
end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :band
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
  has_one :record_label, dependent: :destroy 
  has_many :albums, dependent: :destroy
  has_one_attached :picture
  belongs_to :user
end

app/models/record_label.rb
class RecordLabel < ApplicationRecord
  belongs_to :band
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bands
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # rescue_from CanCan::AccessDenied do |exception|
  #    flash[:authorization_error] = "Not authorized to perform that action ❌"
  #    redirect_to listings_path
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :authenticate_user! #has to be at the top so you have to be signed in
  before_action :find_band ,only: [:show, :edit, :update]
  # before_action :set_band_listing, only: [:edit, :update, :destroy]


  def index
    @bands = Band.all
    #this is a visit count for the page, can reset with clearing the cookies
    if !session[:count]  
      session[:count] = 1
    else
      session[:count] += 1
    end
  end

  def show
    # @band = Band.find(params[:id])  Can remove these because of find_band method, as well as edit, and update
  end

  def new
    @band = Band.new
  end

  def create
    # @band = Band.new(band_params)
    # @band.save

    # redirect_to @band
    # need to have devise connected for this
    @band = current_user.bands.create(band_params)
    if @band.errors.any?
      render :new
    else
      flash[:success] = "You successfully created a new band!"
      redirect_to bands_path
    end 
  end

  def edit
    # @band =  Band.find(params[:id])
  end

  def update
    # @band = Band.find(params[:id])
    @band.update(band_params)

    redirect_to @band
  end

  def destroy
    @band.destroy

    redirect_to bands_path
  end

  private

  def band_params
    params.require(:band).permit(:name, :album_title, :date_started, :picture)
  end

  def find_band
    @band = Band.find(params[:id])
  end
  # if statement authorization
  # def set_band_listing
  #   id = params[:id]
  #   @band = current_user.bands.find_by_id(id)

  #   if @band == nil
  #     redirect_to band_path
  #   end
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/_card.html.erb
<div class="card text-center my-3 col-md-4 col-xs-12" style="max-width:30%; min-width:18rem;">
  <%= image_tag picture_for(band) , alt: "#{band.name} image", class: 'card-img-top img_fluid' %>
  <div class="card-body">
    <h5 class="card-title"><%= band.name %></h5>
    <h6 class="card-subtitle mb-2 text-muted"><%= band.album_title %></h6>
    <%= link_to 'View', band_path(band), class: 'btn btn-primary' %>
  </div>
</div>

app/views/bands/_form.html.erb
<%= form_with model: @band, local: true do|form| %>

<div class="form-container">
  <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
      <%= form.label :album_title %>
      <%= form.text_field :album_title, class: 'form-control' %>
  </div>

  <div class="form-group">
      <%= form.label :date_started %>
      <%= date_field(:user, :born_on) %>
  </div>
  
  <div class="form-group">
      <%= form.label :picture %> 
      <%= form.file_field :picture, accept: 'image/png,image/gif,image/jpeg,image/jpg' %>
  </div>

  <div class="custom-file">
    <%= form.label :image, class: 'custom-file-label' %>
    <%= form.file_field :image, class: 'custom-file-input', id: 'customFile' %>
  </div>
  
  <div>
    <%= form.submit class: "btn btn-success my-2" %>
  </div>
</div>
<% end %>

app/views/bands/edit.html.erb
<h1>Edit <%= @band.name %></h1>

<%= render 'form' %>

<%= link_to 'Back', band_path(@band) %>

app/views/bands/index.html.erb
<h1>All Bands</h1>

<div class="row justify-content-around">
  <% @bands.each do |band| %>
    <%= render 'card', band: band %>
  <% end %>

</div>

<%# <%= link_to "edit", edit_band_path(band.id) if current_user.id == band.id %> 
<%# <p><%= link_to band.name, band_path(band) : <%= band.album_title</p> %> 

app/views/bands/new.html.erb
<%# create a from here %>

<h1>Create a New Band</h1>

<%= render 'form' %>

<%= link_to 'Back', bands_path %>

app/views/bands/show.html.erb
<h1><%= @band.name %></h1>

<h3>Album: <%= @band.album_title %></h3>

<h3>Date formed: <%= @band.date_started %></h3>
<%= image_tag @band.picture if @band.picture.attached? %>

<div class="form-helpers">
  <% if current_user.id == @band.user.id %>
    <%= link_to 'Edit', edit_band_path(@band) %>
    <%= link_to 'Delete', band_path(@band), method: :delete, data: { confirm: "Really want to delete #{@band.name}?"} %>
  <% end %>
    <%= link_to 'Back', bands_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <div class="logout-button">
      <% if user_signed_in? %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Login", new_user_session_path %>
      <% end %>
    </div>
  </body>
</html>